name: laboratorul3
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Updated cupertino_icons to the latest version
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Updated flutter_lints to the latest version
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wines.json
    - assets/wine1.png
    - assets/wine2.png
    - assets/wine3.png
    - assets/wine4.png
    - assets/pngwing 2.png
    - assets/white_wine.png
    - assets/rose_wine.png
    - assets/sparkling_wine.png
